---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "core-provider.fullname" . }}-compositions-max-name-length-binding
spec:
  policyName: {{ include "core-provider.fullname" . }}-compositions-max-name-length-policy 
  validationActions: ["Deny"]
  matchResources:
    namespaceSelector:
      {}